### ISSUE TITLE
Cannot find main

### ISSUE THREAD

**Issue by beefy** [ASLive/webserver#2]
```
3:57:25 PM: Executing task ' bootRun --scan --stacktrace'...

:compileKotlin UP-TO-DATE
:compileJava NO-SOURCE
:processResources UP-TO-DATE
:classes UP-TO-DATE
Error: Could not find or load main class main.kotlin.aslive.Application
```

on `kotlin-porting` branch

**Comment by beefy** [comment]
example kotlin gradle file:

https://github.com/JetBrains/kotlin-examples/blob/master/gradle/hello-world/build.gradle

**Comment by evanradcliffe** [comment]
That file contains a line `mainClassName = 'demo.HelloWorldKt'`

Do we need that line in our build.gradle? `mainClassName = 'main.kotlin.aslive.Application` 

I don't really know gradle but [this post](https://stackoverflow.com/a/24925020) makes me think we need it because gradle can't find a main Java file since it's Kotlin.
